import Head from "next/head";
import { About, Contact, Main, Projects, Skills } from "../components";

const Home = () => {
  return (
    <div >
      <Head>
        <title>Oded-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
};

export default Home;
